name: CI for TimeCLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Sync dependencies with uv
        run: |
          uv sync
      
      - name: Run pytest
        run: |
          uv run pytest tests/
      
      - name: Lint with flake8
        run: |
          uv run flake8 . --exit-zero
      
      - name: Builder Docker image
        run: |
          docker build -t timecli:latest .